# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b205e261745b52d4ac47f5f3122a7f83d8c04a9565c6657fb576168c4e048efb30fac7d901f083db76da5753a03c1ba72f490bbed13a31508a0f96030adfb5

test:
  secret_key_base: 323e5238c90bff6d8cb9a933704f394bf20d4c384c13fe3951288401ba266cd9d9fd21a95c60d4e3a2f6bfcc8c5848d948a1170a0608dfed43d6cbc1efac87fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
